example_stories = [
  # story 1
  {
    "title": "Can every single one of us surround our whole planet?",
    "clips": [
      # clip 1: If every single one of us ... That is a sir cool. (9.1 - 84.62)
      {
        "start_index": 4,
        "end_index": 193
      }
    ]
  },
  # story 2
  {
    "title": "What is \"rolling\" and how to design the perfect road instead of the perfect wheel!",
    "clips": [
      # clip 1: what is rolling? ... allows it to roll smoothly. (93.74000000000001 - 167.16)
      {
        "start_index": 206,
        "end_index": 387
      }
    ]
  },
  # story 3
  {
    "title": "What is the fastest path to roll down to a point?",
    "clips": [
      # clip 1: let me ask you this ... cycloid satisfies, snells law, everywhere. (284.62 - 478.88)
      {
        "start_index": 711,
        "end_index": 1234
      }
    ]
  },
  # story 4
  {
    "title": "The physical brachistochrone & it's bizzare tautochrone property",
    "clips": [
      # clip 1: let me ask you this ... but not directly below? (284.62 - 294.3)
      {
        "start_index": 711,
        "end_index": 741
      },
      # clip 2: a cycloid provides the perfect balance ... start building. (492.44 - 510.08)
      {
        "start_index": 1268,
        "end_index": 1319
      },
      # clip 3: Are you ready? ... slowest way to get there. (1012.34 - 1032.78)
      {
        "start_index": 2420,
        "end_index": 2467
      },
      # clip 4: I'm gonna remove the straight line ... But that's boring. (1195.54 - 1242.18)
      {
        "start_index": 2868,
        "end_index": 2995
      },
      # clip 5: I think the same person ... That was awesome. (1337.16 - 1365.86)
      {
        "start_index": 3266,
        "end_index": 3340
      }
    ]
  },
  # story 5
  {
    "title": "Exploring the old school Spirograph toy & the amazing Tusi couple!",
    "clips": [
      # clip 1: let's take some time to appreciate ... when bought in Oceola, Missouri. (864.92 - 989.9)
      {
        "start_index": 2059,
        "end_index": 2396
      }
    ]
  }
]