example_stories = [
  {
    "story_id": 1,
    "why_complete": "Explores the concept of surrounding the planet with people. Also includes an interesting side fact of ring being larger than moon's orbit.",
    "title": "Can every single one of us surround our whole planet?",
    "clips": [
      # clip 1: If every single one of us ... That is a sir cool. (9.1 - 84.62)
      {
        "start_index": 4,
        "end_index": 193,
        "reason": "question posed and answered + covered full side quest"
      }
    ]
  },
  {
    "story_id": 2,
    "why_complete": "Explores the brachistochrone problem and provides the answer of cycloid curve with detailed explanation.",
    "title": "What is the fastest path to roll down to a point?",
    "clips": [
      # clip 1: let me ask you this ... cycloid satisfies, snells law, everywhere. (284.62 - 478.88)
      {
        "start_index": 711,
        "end_index": 1234,
        "reason": "question posed, explored and answered"
      }
    ]
  },
  {
    "story_id": 3,
    "why_complete": "Explains the brachistochrone curve and its tautochrone property with examples and demonstrations.",
    "title": "The physical brachistochrone & it's bizzare tautochrone property",
    "clips": [
      # clip 1: let me ask you this ... but not directly below? (284.62 - 294.3)
      {
        "start_index": 711,
        "end_index": 741,
        "reason": "question posed"
      },
      # clip 2: a cycloid provides the perfect balance ... start building. (492.44 - 510.08)
      {
        "start_index": 1268,
        "end_index": 1319,
        "reason": "answered + started to demonstrate"
      },
      # clip 3: Are you ready? ... slowest way to get there. (1012.34 - 1032.78)
      {
        "start_index": 2420,
        "end_index": 2467,
        "reason": "demonstration result and prooved"
      },
      # clip 4: I'm gonna remove the straight line ... But that's boring. (1195.54 - 1242.18)
      {
        "start_index": 2868,
        "end_index": 2995,
        "reason": "side quest about tautochrone property"
      },
      # clip 5: I think the same person ... That was awesome. (1337.16 - 1365.86)
      {
        "start_index": 3266,
        "end_index": 3340,
        "reason": "conclusion of tautochrone property demonstration"
      }
    ]
  }
]